# Development/Dockerfile

FROM python:3.10-slim

# Cài gói hệ thống
RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    python3-dev \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Làm việc tại thư mục code
WORKDIR /app

# Sao chép toàn bộ code (dù Dockerfile nằm ở Development/)
COPY . .

# Cài requirements
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Chạy pipeline chính
CMD ["python", "src/pipelines/data_pipeline.py"]
