experiment:
  run_name: "run"

data:
  path: "data/raw/train/"
  freq: "5min"
  split_ratio: 1
  traffic_direction: "in"
  processed_data_path: "data/processed/train_data.csv"
  processed_data_parquet_path: "data/processed/train_data.parquet"
  feature_store_path: "feature_repo/feature_repo"  
model:
  nhits:
    h: 12
    input_size: 72
    max_steps: 500
    lr: 1e-3
    batch_size: 32
    n_blocks: [2, 2, 2]        # List[int], mỗi stack có 3 block
    mlp_units: [[512, 512], [512, 512], [512, 512]]   # List[List[int]]
    early_stop_patience_steps: -1
  nbeatsx:
    h: 12
    input_size: 72
    hist_exog_list: ["lag_5min", "lag_30min", "rolling_mean", "rolling_std", "lag_2h"]
    max_steps: 100
    lr: 1e-3
    batch_size: 32
    n_blocks: [2, 2, 2]       
    mlp_units: [[512, 512], [512, 512], [512, 512]]   
    early_stop_patience_steps: -1
  patchtst:
    h: 12
    input_size: 72
    patch_len: 24
    stride: 24
    max_steps: 500
    hidden_size: 512
    linear_hidden_size: 1024
    encoder_layers: 6
    dropout: 0.2
    fc_dropout: 0.2
    attn_dropout: 0.1
    lr: 1e-4
    scaler_type: 'robust'
    revin: False
    batch_size: 32
    n_heads: 16       
    early_stop_patience_steps: -1
  timesnet:
    h: 12
    input_size: 72
    max_steps: 500
    top_k: 5
    num_kernels: 6
    conv_hidden_size: 64
    hidden_size: 64
    dropout: 0.1
    lr: 1e-4
    batch_size: 32
    early_stop_patience_steps: -1

log:
  data_log: "logs/data_pipeline.log"
  training_log: "logs/training.log"
  evaluation_log: "logs/evaluation.log"