services:
  feast:
    build:
      context: .
      dockerfile: Dockerfile_feast
    # Thư mục làm việc nên là nơi chứa file feature_store.yaml
    working_dir: /app/feature_repo/feature_repo
    volumes:
      # Mount toàn bộ thư mục dự án vào /app trong container
      - .:/app
    # 'feast apply' sẽ đọc các định nghĩa feature và cập nhật registry.
    # Đường dẫn FileSource trong feature view của bạn nên là đường dẫn tương đối,
    # ví dụ: ../../data/processed/train_data.parquet
    command: ["feast", "apply"]
