path: "data/raw/train/"
freq: "5min"
split_ratio: 0.8
traffic_direction: "in"
processed_data_path: "data/processed/train_data.csv"
processed_data_parquet_path: "data/processed/train_data.parquet"
feature_store_path: "feature_repo/feature_repo" 